GRID_TAB_NAME = "Grid"
FILLS_TAB_NAME = "Fills"
HEALTH_TAB_NAME = "Health"

# Grid Tab Columns
COL_ROW_ID = "ROW_ID"
COL_TYPE = "TYPE"
COL_TRIGGER_PRICE = "TRIGGER_PRICE"
COL_LIMIT_PRICE = "LIMIT_PRICE"
COL_QUANTITY = "QUANTITY"
COL_ACTIVE = "ACTIVE"
COL_NOTES = "NOTES"

# Fills Tab Columns
COL_TIMESTAMP = "TIMESTAMP"
COL_FILL_ROW_ID = "ROW_ID"
COL_FILL_TYPE = "TYPE"
COL_FILLED_PRICE = "FILLED_PRICE"
COL_FILLED_QTY = "FILLED_QTY"
COL_ORDER_ID = "ORDER_ID"
